/// Data models for the OTP verification response.
///
/// This file contains models that represent the response received from the API
/// when verifying an OTP. It includes the main response model and a nested data model
/// containing user information.
import 'package:json_annotation/json_annotation.dart';
import 'package:mera_bazaar/src/domain/entities/auth/verify_otp_response_entity.dart';

part 'verify_otp_response.g.dart';

/// A data model that represents the response from verifying an OTP.
///
/// This class is annotated with [JsonSerializable] to enable automatic JSON serialization.
/// It contains fields that match the API response structure and provides methods for
/// JSON conversion and entity mapping.
@JsonSerializable()
class VerifyOtpResponse {
  /// Indicates whether the OTP verification operation was successful
  bool? success;

  /// A message describing the result of the operation
  String? message;

  /// Indicates whether an error occurred during the operation
  bool? error;

  /// The user data returned upon successful verification
  VerifyOtpData? data;

  /// Creates a new instance of [VerifyOtpResponse].
  ///
  /// All parameters are optional and can be null.
  VerifyOtpResponse({this.success, this.message, this.error, this.data});

  /// Creates a [VerifyOtpResponse] instance from a JSON map.
  ///
  /// This factory constructor is automatically generated by the json_serializable package.
  /// It converts a JSON map into a [VerifyOtpResponse] object.
  factory VerifyOtpResponse.formJson(Map<String, dynamic> json) =>
      _$VerifyOtpResponseFromJson(json);

  /// Converts this [VerifyOtpResponse] instance to a JSON map.
  ///
  /// This method is automatically generated by the json_serializable package.
  /// It converts the [VerifyOtpResponse] object into a JSON map.
  Map<String, dynamic> toJson() => _$VerifyOtpResponseToJson(this);

  /// Converts this data model to an entity.
  ///
  /// This method creates a [VerifyOtpResponseEntity] with the same data as this model.
  /// The entity is used in the domain layer and is independent of the data layer.
  VerifyOtpResponseEntity toEntity() {
    return VerifyOtpResponseEntity(
      success: success,
      message: message,
      error: error,
      data: data,
    );
  }
}

/// A data model that represents the user data returned upon successful OTP verification.
///
/// This class is annotated with [JsonSerializable] to enable automatic JSON serialization.
/// It contains fields that match the user data structure in the API response.
@JsonSerializable()
class VerifyOtpData {
  /// The authentication token for the verified user
  String? token;

  /// The phone number of the verified user
  String? number;

  /// The name of the verified user
  String? name;

  /// The profile URL of the verified user
  String? profileUrl;

  /// The email address of the verified user
  String? email;

  /// Creates a new instance of [VerifyOtpData].
  ///
  /// All fields are optional and can be null.
  VerifyOtpData();

  /// Creates a [VerifyOtpData] instance from a JSON map.
  ///
  /// This factory constructor is automatically generated by the json_serializable package.
  /// It converts a JSON map into a [VerifyOtpData] object.
  factory VerifyOtpData.fromJson(Map<String, dynamic> json) =>
      _$VerifyOtpDataFromJson(json);

  /// Converts this [VerifyOtpData] instance to a JSON map.
  ///
  /// This method is automatically generated by the json_serializable package.
  /// It converts the [VerifyOtpData] object into a JSON map.
  Map<String, dynamic> toJson() => _$VerifyOtpDataToJson(this);
}
