arb-dir: lib/src/config/localization
template-arb-file: intl_en.arb
output-dir: lib/src/config/localization
output_localization-file: app_localization.dart
nullable-getter: false
synthetic-package: false