/// Data model for the OTP sending response.
///
/// This model represents the response received from the API when sending an OTP.
/// It includes fields for success status, message, and error status.
/// The model can be serialized to and from JSON, and can be converted to an entity.
import 'package:json_annotation/json_annotation.dart';
import 'package:mera_bazaar/src/domain/entities/auth/send_otp_response_entity.dart';

part 'send_otp_response.g.dart';

/// A data model that represents the response from sending an OTP.
///
/// This class is annotated with [JsonSerializable] to enable automatic JSON serialization.
/// It contains fields that match the API response structure and provides methods for
/// JSON conversion and entity mapping.
@JsonSerializable()
class SendOtpResponse {
  /// Indicates whether the OTP sending operation was successful
  bool? success;

  /// A message describing the result of the operation
  String? message;

  /// Indicates whether an error occurred during the operation
  bool? error;

  /// Creates a new instance of [SendOtpResponse].
  ///
  /// All parameters are optional and can be null.
  SendOtpResponse({this.success, this.message, this.error});

  /// Creates a [SendOtpResponse] instance from a JSON map.
  ///
  /// This factory constructor is automatically generated by the json_serializable package.
  /// It converts a JSON map into a [SendOtpResponse] object.
  factory SendOtpResponse.fromJson(Map<String, dynamic> json) =>
      _$SendOtpResponseFromJson(json);

  /// Converts this [SendOtpResponse] instance to a JSON map.
  ///
  /// This method is automatically generated by the json_serializable package.
  /// It converts the [SendOtpResponse] object into a JSON map.
  Map<String, dynamic> toJson() => _$SendOtpResponseToJson(this);

  /// Converts this data model to an entity.
  ///
  /// This method creates a [SendOtpResponseEntity] with the same data as this model.
  /// The entity is used in the domain layer and is independent of the data layer.
  SendOtpResponseEntity toEntity() {
    return SendOtpResponseEntity(
      success: success,
      message: message,
      error: error,
    );
  }
}
