/// Data model for the user profile response.
///
/// This model represents the response received from the API when fetching a user's profile.
/// It includes fields for the user's name, email, mobile number, and profile URL.
/// The model can be serialized to and from JSON, and can be converted to an entity.
import 'package:json_annotation/json_annotation.dart';
import 'package:mera_bazaar/src/domain/entities/auth/get_user_profile_entity.dart';

part 'get_user_profile_response.g.dart';

/// A data model that represents the user profile data returned from the API.
///
/// This class is annotated with [JsonSerializable] to enable automatic JSON serialization.
/// It contains fields that match the API response structure and provides methods for
/// JSON conversion and entity mapping.
@JsonSerializable()
class GetUserProfileResponse {
  /// The user's full name
  @JsonKey(name: "name")
  String? name;

  /// The user's email address
  @JsonKey(name: "email")
  String? email;

  /// The user's mobile phone number
  @JsonKey(name: "mobile_number")
  String? mobileNumber;

  /// The URL of the user's profile picture
  @JsonKey(name: "profile_url")
  String? profileUrl;

  /// Creates a new instance of [GetUserProfileResponse].
  ///
  /// All parameters are optional and can be null.
  GetUserProfileResponse({
    this.name,
    this.email,
    this.mobileNumber,
    this.profileUrl,
  });

  /// Creates a [GetUserProfileResponse] instance from a JSON map.
  ///
  /// This factory constructor is automatically generated by the json_serializable package.
  /// It converts a JSON map into a [GetUserProfileResponse] object.
  factory GetUserProfileResponse.fromJson(Map<String, dynamic> json) =>
      _$GetUserProfileResponseFromJson(json);

  /// Converts this [GetUserProfileResponse] instance to a JSON map.
  ///
  /// This method is automatically generated by the json_serializable package.
  /// It converts the [GetUserProfileResponse] object into a JSON map.
  Map<String, dynamic> toJson() => _$GetUserProfileResponseToJson(this);

  /// Converts this data model to an entity.
  ///
  /// This method creates a [GetUserProfileEntity] with the same data as this model.
  /// The entity is used in the domain layer and is independent of the data layer.
  GetUserProfileEntity toEntity() {
    return GetUserProfileEntity(
      name: name,
      email: email,
      mobileNumber: mobileNumber,
      imageUrl: profileUrl,
    );
  }
}
